import type { Metadata } from "next";
import { Marvel } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/components/NavBar";

// const marvel = Marvel();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
