import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./ui/components/NavBar";

// adding local font using next/font
const komika = localFont({ src: "../public/fonts/komika.ttf" });

export const metadata: Metadata = {
  title: "G-Marvel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={komika.className}>
        <NavBar />
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
